# -*- coding: utf-8 -*-
"""
Titanic_ML.ipynb

Automatically generated by Colab.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
from numpy import median
import torch
import torch.nn as nn
import torch.nn.functional as F
import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
# %matplotlib inline

class Model(nn.Module):
    def __init__(self, input_feature=11, h1=16, h2=8, output_feature=2):
      super().__init__()
      self.fc1 = nn.Linear(input_feature, h1)
      self.fc2 = nn.Linear(h1, h2)
      self.out = nn.Linear(h2, output_feature)

    def forward(self, x):
      x = F.relu(self.fc1(x))
      x = F.relu(self.fc2(x))
      x = self.out(x)
      return x

torch.manual_seed(2)
model = Model()

url1 = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
my_df = pd.read_csv(url1)
my_df



# clean up data

my_df = my_df.drop(["PassengerId"], axis=1)
my_df = my_df.drop(["Fare"], axis=1)

rare_titles = ["Lady", "the Countess","Capt", "Col", "Don", "Dr", "Major", "Rev", "Sir", "Jonkheer"]

# determinate gender
my_df["Sex"] = my_df["Sex"].replace("female", 0.0) # female = 0.0
my_df["Sex"] = my_df["Sex"].replace("male", 1.0) # male = 1.0 (obviously)

# splitting names and only have their title
my_df["Name"] = my_df["Name"].apply(lambda x: x.split(",")[1].split(".")[0].strip())
my_df["Name"] = my_df["Name"].replace(rare_titles, "Rare")
my_df["Name"] = my_df["Name"].replace(["Mlle", "Ms"], "Miss")
my_df["Name"] = my_df["Name"].replace("Mme", "Mrs")

# encoding titles
title_mapping = {"Master": 0.0, "Miss": 1.0, "Mr": 2.0, "Mrs": 3.0, "Rare": 4.0}
my_df["Name"] = my_df["Name"].map(title_mapping)

# cleaning up ages
my_df["Age"] = my_df["Age"].fillna(my_df.groupby("Name")["Age"].transform("median")) # I calculated the median from each group to insert to replace NaN

# deleting tickets and creating a "Group" category
ticket_count = my_df["Ticket"].value_counts()
my_df["Group"] = (my_df["Ticket"].map(ticket_count) > 1).astype(float)
my_df = my_df.drop("Ticket", axis=1)

# detect if passanger has a cabin documented --> historical context: important people that had likely more survival chance
my_df["Cabins"] = my_df["Cabin"].notna().astype(float) # is Nan? -> 0.0, else 1.0
my_df = my_df.drop(columns=["Cabin"])

# embarked: split into 3 groups to not disrupt the data
my_df["Embarked"] = my_df["Embarked"].fillna("S")
my_df = pd.get_dummies(my_df, columns=["Embarked"], dtype=float) # how many variables are in the column? create new columns dependent of the variables: Labeling from 0.0 to 1.0
my_df

# train test split X, y
X = my_df.drop("Survived", axis=1)
y = my_df["Survived"]

# convert to numpy arrays
X = X.values
y = y.values

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

# converting X features to float Tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

# converting y labels to tensors long
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

# measure loss
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# model train
epochs = 100
losses = []
for i in range(epochs):
  # forward
  y_pred = model.forward(X_train)
  loss = criterion(y_pred, y_train) # loss measure

  losses.append(loss.detach().numpy())

  if i % 50 == 0:
    print(f"Epoch: {i} --> loss {loss}")

  # backpropagation
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

# graph
plt.plot(range(epochs), losses)
plt.ylabel("loss")
plt.xlabel("epoch")

# evaluate model on test data set
with torch.no_grad(): # turn off backpropagation
  y_eval = model.forward(X_test)
  loss = criterion(y_eval, y_test) # find the loss

loss

correct = 0
with torch.no_grad():
  for i, data in enumerate(X_test):
    y_val = model.forward(data)

    # will tell if passengers survived or not
    print(f"{i+1}.) {str(y_val)} \t {y_test[i]} \t {y_val.argmax().item()}")

    if y_val.argmax().item() == y_test[i]:
      correct += 1

print(f"correct {correct} \t {correct/len(X_test)}")

test_df = pd.read_csv("test.csv")
test_df

# clean up data the seond time for test (almost copy-paste)

rare_titles = ["Lady", "the Countess","Capt", "Col", "Don", "Dr", "Major", "Rev", "Sir", "Jonkheer", "Dona"]

# determinate gender
test_df["Sex"] = test_df["Sex"].replace("female", 0.0) # female = 0.0
test_df["Sex"] = test_df["Sex"].replace("male", 1.0) # male = 1.0 (obviously)

# splitting names and only have their title
test_df["Name"] = test_df["Name"].apply(lambda x: x.split(",")[1].split(".")[0].strip())
test_df["Name"] = test_df["Name"].replace(rare_titles, "Rare")
test_df["Name"] = test_df["Name"].replace(["Mlle", "Ms"], "Miss")
test_df["Name"] = test_df["Name"].replace("Mme", "Mrs")

# encoding titles
title_mapping = {"Master": 0.0, "Miss": 1.0, "Mr": 2.0, "Mrs": 3.0, "Rare": 4.0}
test_df["Name"] = test_df["Name"].map(title_mapping)

# cleaning up ages
test_df["Age"] = test_df["Age"].fillna(test_df.groupby("Name")["Age"].transform("median")) # I calculated the median from each group to insert to replace NaN

# deleting tickets and creating a "Group" category
ticket_count = test_df["Ticket"].value_counts()
test_df["Group"] = (test_df["Ticket"].map(ticket_count) > 1).astype(float)
test_df = test_df.drop("Ticket", axis=1)

# detect if passanger has a cabin documented --> historical context: important people that had likely more survival chance
test_df["Cabins"] = test_df["Cabin"].notna().astype(float) # is Nan? -> 0.0, else 1.0
test_df = test_df.drop(columns=["Cabin"])

# embarked: split into 3 groups to not disrupt the data
test_df["Embarked"] = test_df["Embarked"].fillna("S")
test_df = pd.get_dummies(test_df, columns=["Embarked"], dtype=float) # how many variables are in the column? create new columns dependent of the variables: Labeling from 0.0 to 1.0
test_df

passengerID = test_df["PassengerId"]

# dropping passangerId, fare
X_test_data = test_df.drop(["PassengerId", "Fare"], axis=1)

# filling in missing datasets with the median
X_test_data = X_test_data.fillna(X_test_data.median())

X_sub = torch.FloatTensor(X_test_data.values)
with torch.no_grad():
  prediction = model(X_sub).argmax(dim=1).numpy()

pd.DataFrame({"PassengerId": passengerID,
              "Survived": prediction}).to_csv("submission.csv", index=False)
